require_relative '../node_modules/react-native/scripts/react_native_pods'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'

platform :ios, '10.0'

target 'AmiApp' do
  config = use_native_modules!

  use_react_native!(:path => config["reactNativePath"])


  pod 'react-native-print', :path => '../node_modules/react-native-print'

  pod 'lottie-react-native', :path => '../node_modules/lottie-react-native'

  target 'AmiAppTests' do
    inherit! :complete
    # Pods for testing
  end

  # Enables Flipper.
  #
  # Note that if you have use_frameworks! enabled, Flipper will not work and
  # you should disable these next few lines.
  use_flipper!
  post_install do |installer|
    flipper_post_install(installer)
  end
end

target 'AmiApp-tvOS' do
  # Pods for AmiApp-tvOS

  target 'AmiApp-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end
end
